//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CumminsPrototipo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROTOTIPO_GRUPO_EMAIL
    {
        public long prototipoGrupoEmailId { get; set; }
        public long prototipoId { get; set; }
        public long grupoEmailId { get; set; }
        public string estacaoTrabalhoCod { get; set; }
    
        public virtual GRUPO_EMAIL GRUPO_EMAIL { get; set; }
        public virtual PROTOTIPO PROTOTIPO { get; set; }
    }
}
